### ISSUE TITLE
GhostConnectionPosition is not updating

### ISSUE THREAD

**Issue by Lrakulka** [moetsi/Unity-DOTS-Multiplayer-XR-Sample#1]
It looks like the logic is missing a System that would update the `GhostConnectionPosition`

Like here https://github.com/Unity-Technologies/multiplayer/blob/7b881836a783e3fc37e50438f553b8939a05e5a4/sampleproject/Assets/Samples/Asteroids/Server/Systems/UpdateConnectionPositionSystem.cs

**Comment by adammpolak** [comment]
@Lrakulka  thank you for reaching out!

Not sure what step you are on in the tutorial but it get's updated and then removed for different reasons. Let me know what you think!

**Comment by adammpolak** [comment]
@Lrakulka I believe what you are looking for is here: https://dots-tutorial.moetsi.com/multiplayer/send-ghosts-with-dots-netcode

**Comment by Lrakulka** [comment]
@adammpolak You are using this strategy https://github.com/moetsi/Unity-DOTS-Multiplayer-XR-Sample/blob/b91d306e97ab1d6c774bf24b4b2482d5ef2e50c0/Assets/Scripts%20and%20Prefabs/Multiplayer%20Setup/ClientServerConnectionControl.cs#L47 to decide importance for ghost, but you don't have a system that updates `Position` variable in `GhostConnectionPosition` component that is why logic thinks that all your ghosts position is (0,0,0)

**Comment by adammpolak** [comment]
I believe you are looking for this line @Lrakulka :https://github.com/moetsi/Unity-DOTS-Multiplayer-XR-Sample/blob/4374b7625aad31d55958281375519a5b7a75357c/Assets/Scripts%20and%20Prefabs/Server/Systems/PlayerRelevancySphereSystem.cs#L79

That is where the position is updated

**Comment by Lrakulka** [comment]
@adammpolak I tried to fetch your repository and check if the issue (that I think exists) is present or not, but I was facing a problem connecting the client to the server that is why I could not start the game and check it. 
My proposition, I created two patches with logic that will reveal if the code contains the issue or not. Would you be kind to check it? (or we can wait till I reach that portion of the tutorial, figure out what was the issue with the client connection, and check by myself that issue)
1 Patch - just check if the issue present
2 Patch - issue checker with the system that resolves it.
Patches link https://drive.google.com/drive/folders/1wasePJHX84M9lXpBF_yzrMu_eYRR6yNc?usp=sharing

**Comment by adammpolak** [comment]
@Lrakulka sorry you ran the main branch and you were not able to host a local game?

Do you mind letting me know what branch you tried to start the project in?

**Comment by Lrakulka** [comment]
@adammpolak I tried the main branch and branch `GhostRelevancyMode-and-Clean-Up`
The problem is not in the code, but in Unity itself
It can't chew throw DOTS + UI toolkit together.
on Unity 2020.1.17f1 it does not throw any exception, but Navigation Scene is frozen, I can't press any button or scroll.
on other Unity versions, I have this issue https://forum.unity.com/threads/subscenes-ui-entity-header-failed-to-load.1007609/  
Navigation Scene is working but on MainScene I am receiving issue with subscene.
EDIT
I fixed 2020.1.17f1 for me, I was using `System Event`, but not `System Event (UI Toolkit)`, more later Unity versions can work with `System Event`

**Comment by Lrakulka** [comment]
@adammpolak So I finally reach that point of tutorial to check logic by myself. I confirm that the issue is present.
Without System that updates the GhostConnectionPosition
![WithoutSystem](https://user-images.githubusercontent.com/6137277/129470706-15316bef-5e66-4ae9-8232-0b0c23c2a249.JPG)
With System
![WithSystem](https://user-images.githubusercontent.com/6137277/129470707-dcef15c7-2404-4d78-9659-59735d64c69b.JPG)

By the way, you will not need that system if your importance strategy does not use Ghost position, the `GhostDistanceImportance.NoScaleFunctionPointer` strategy just uses the base priority that you set in the configuration.

**Comment by adammpolak** [comment]
@Lrakulka what do you think would be most helpful as an update?

**Comment by Lrakulka** [comment]
@adammpolak I would add that system https://github.com/Unity-Technologies/multiplayer/blob/7b881836a783e3fc37e50438f553b8939a05e5a4/sampleproject/Assets/Samples/Asteroids/Server/Systems/UpdateConnectionPositionSystem.cs

**Comment by adammpolak** [comment]
I think I need to look into this deeper. It seems like the file you are referring to from the original Asteroids project is updating the position the same way this project's system is: https://github.com/moetsi/Unity-DOTS-Multiplayer-XR-Sample/blob/4374b7625aad31d55958281375519a5b7a75357c/Assets/Scripts%20and%20Prefabs/Server/Systems/PlayerRelevancySphereSystem.cs#L79

I believe both these systems perform the same function.

**Comment by adammpolak** [comment]
Hello, after opening this project from scratch from the main branch the relevancy sphere is working as expected. Closing this issue.
