### ISSUE TITLE
Incorrect Tag name `LocalGame`->`localGame`

### ISSUE THREAD

**Issue by Lrakulka** [moetsi/Unity-DOTS-Multiplayer-XR-Sample#3]
Page: https://dots-tutorial.moetsi.com/ui-builder-and-ui-toolkit/create-a-list-view-in-unity-ui-builder
Lines: 
`Add a "LocalGame" tag to the LocalGame GameObject`
`...selected and choose the last option "Add Tag..." and click the + under Tags and type "LocalGame"...`

All code snippet refers to this tag as `localGame`, since Tag name is case sensitive it's creating an issue.
`UnityException: Tag: localGame is not defined.`

Note: in prev pages, the tag name was starting from the upper case.

**Comment by adammpolak** [comment]
Thank you, corrected!
