### ISSUE TITLE
Cannot convert from 'UnityEngine.GUILayoutUtility.LayoutCache' to 'int'

### ISSUE THREAD

**Issue by dyhmichail** [moetsi/Unity-DOTS-Multiplayer-XR-Sample#5]
Starting project on Unity version 2020.3.18 cause an error
https://forum.unity.com/threads/ui-toolkit-1-0-0-preview-14-unity-2021-1-16f1-bug.1150016/
Looks like that project simply must be updated to the latest Unity version and latest packages.

**Comment by adammpolak** [comment]
Appreciate the heads up @dyhmichail , working through the Unity versioning.

**Comment by adammpolak** [comment]
@dyhmichail currently recommending this project be opened with 2020.1.17f1, closing this issue.
